concatdm
InnopolisUni/innofw pull request #155
Opened 2023-04-12 12:29 UTC by paNikitin

2023-04-14 14:46 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/drugprot.py
> +            #self.train_dataset.with_format("pt"),
это не нужно?

2023-04-14 14:46 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/concatenated_datamodule.py
> +
решили его пока в pipeline.py не внедрять?

2023-04-14 15:27 UTC, paNikitin commented on innofw/core/datamodules/lightning_datamodules/drugprot.py
> +            #self.train_dataset.with_format("pt"),
сделал внутри сетапа

2023-04-14 15:28 UTC, paNikitin commented on innofw/core/datamodules/lightning_datamodules/drugprot.py
> +                result[key][batch_index, :current_len] =  torch.tensor(instance[key][:current_len], dtype=torch.long)
+

2023-04-14 15:29 UTC, paNikitin commented on config/experiments/EXPERIMENT.yaml
> +# @package _global_
Вообще это можно удалить, потому что это копия существующего

2023-04-14 15:30 UTC, paNikitin commented on innofw/core/datamodules/lightning_datamodules/concatenated_datamodule.py
> +
в пайплайне

2023-04-17 10:12 UTC, QazyBi requested changes

2023-04-17 10:12 UTC, QazyBi commented on innofw/pipeline.py
> +        cfg._dataset_dict,
я думаю другие эксперименты не будут запускаться из-за этой строчки

2023-04-17 10:12 UTC, QazyBi commented on innofw/pipeline.py
> +        cfg._dataset_dict,
возможно стоит сделать через try except. Или делать проверку через if. Типа если есть _dataset_dict, тогда создай ConcatDM, если нет то создай датамодуль как обычно

2023-04-17 12:09 UTC, sham1lk requested changes

2023-04-17 12:09 UTC, sham1lk commented on config/experiments/EXPERIMENT.yaml
> +# @package _global_
Предлагаю тогда все же удалить если такой эксперимент уже есть, но я его не вижу, или все же переименовать

2023-04-17 12:09 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/drugprot.py
> +            #self.train_dataset.with_format("pt"),
давай все таки удалим, чтобы код был чище и без не нужных строк кода с  #

2023-04-17 12:09 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/drugprot.py
> +                result[key][batch_index, :current_len] =  torch.tensor(instance[key][:current_len], dtype=torch.long)
можешешь пожалуйста настроить pre-commit install и сделать коммит

2023-04-21 10:00 UTC, sham1lk commented on innofw/pipeline.py
> +    except:
Предлагаю тут указать конкретную ошибку

2023-04-21 10:00 UTC, sham1lk commented on innofw/pipeline.py
> +    except:
тут думаю не стоит писать этот try except

2023-04-24 09:21 UTC, QazyBi requested changes
мб стоило оставить этот файл? Потому что я не вижу другого конфига эксперимента который имеет два датасета

2023-04-24 09:38 UTC, paNikitin commented
> мб стоило оставить этот файл? Потому что я не вижу другого конфига эксперимента который имеет два датасета

тогда верну переименованный файл

2023-04-24 12:54 UTC, QazyBi commented on innofw/pipeline.py
> +        LOGGER.info(lo(next(iter(datamodule.val_dataloader))[SegDataKeys.label]))
I don't think this line will work

2023-07-03 08:23 UTC, merged