tests data utils
InnopolisUni/innofw pull request #158
Opened 2023-04-12 15:49 UTC by 1khazipov

2023-04-13 13:22 UTC, sham1lk requested changes

2023-04-13 13:22 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_transforms/test_db_scan.py
> +
т.е пример и ответ пераметризировать

2023-04-13 13:22 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_preprocessing/test_raster_handler.py
> +    band_files = [
для чего данный лист используется?

2023-04-13 13:22 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_preprocessing/test_satellite_sources.py
> +class TestSentinel2:
тут теста кажется нет

2023-04-13 13:22 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_transforms/test_db_scan.py
> +def test_make_hist():
тут тоже предлагаю сделать через parametrize

2023-04-17 09:10 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_preprocessing/test_crop_raster.py
> +def sample_data(tmp_path: Path) -> None:
tmp_path не испольщуется

2023-04-17 09:11 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_preprocessing/test_band_composer.py
> +def sample_band_files(tmp_path):
Фикстура не используется

2023-04-17 11:23 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_dataset_prep/conftest.py
> +        assert len(list((dst_path / "train" / "images").glob("*"))) == 5
вот эти assert можно перенести в for таким образом 
assert len(list((dst_path / d / "labels").glob("*"))) == 5
assert len(list((dst_path / d / "images").glob("*"))) == 5

2023-04-17 11:24 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_dataset_prep/conftest.py
> +        assert len(list((dst_path / "train" / "images").glob("*"))) == 5
это коммент про код в файле tests/unit/test_utils/test_data_utils/test_dataset_prep/test_prep_yolov5.py

2023-04-17 11:25 UTC, sham1lk commented on tests/unit/test_utils/test_data_utils/test_dataset_prep/conftest.py
> +import shutil
кажется тут не должно быть тестов

2023-04-17 14:52 UTC, QazyBi requested changes

2023-04-17 14:52 UTC, QazyBi commented on tests/unit/test_utils/test_data_utils/test_preprocessing/test_crop_raster.py
> +    assert len(os.listdir(out_folder)) == 0
shouldn't it be 4?

2023-04-17 14:52 UTC, QazyBi commented on tests/unit/test_utils/test_data_utils/test_preprocessing/test_raster_handler.py
> +    assert dataset.ds.count == 4
what is the point of this test?

2023-04-18 10:58 UTC, QazyBi approved these changes

2023-04-18 11:15 UTC, merged