added tutorial on uploading
InnopolisUni/innofw pull request #176
Opened 2023-05-08 14:48 UTC by sadjava

2023-05-11 07:20 UTC, QazyBi requested changes

2023-05-11 07:20 UTC, QazyBi commented on docs/Tutorials - start here/002_Uploading_data_and_checkpoints_to_s3.md
> +1. using python script
by using python script you use the command line interface. I believe you wanted to write Application Programming Interface(API)

2023-05-11 07:20 UTC, QazyBi commented on docs/Tutorials - start here/002_Uploading_data_and_checkpoints_to_s3.md
> +For both uploading data and model using either cli or python script you can omit access_key and secret_key arguments, but they will be asked. So you need to specify them anyway.
"When uploading data or a model using either the command line interface (CLI) or an API, you have the option to omit the access_key and secret_key arguments. The framework will search for these values in the `~/.aws/credentials` and `.env` files. However, if these values are not found, you will be prompted in CLI."

2023-05-11 07:20 UTC, QazyBi commented on docs/Tutorials - start here/002_Uploading_data_and_checkpoints_to_s3.md
> +python innofw/zoo/uploader.py --ckpt_path pretrained/best.pkl
In shell, to achieve line continuation, you typically use a backslash(\) at the end of each line.

2023-05-11 07:20 UTC, QazyBi commented on docs/Tutorials - start here/002_Uploading_data_and_checkpoints_to_s3.md
> +```
You need to add here metrics
```
--metrics '{"some metric": 0.04}'
```

2023-05-11 07:20 UTC, QazyBi commented on docs/Tutorials - start here/002_Uploading_data_and_checkpoints_to_s3.md
> +You can run this python script to upload checkpoint with appropriate values.
You can call this Python function to upload a checkpoint with appropriate values.

2023-05-11 07:20 UTC, QazyBi commented on docs/Tutorials - start here/002_Uploading_data_and_checkpoints_to_s3.md
> +To upload your checkpoint you need to specify config file of your experiment that must be stored in <b>config/experiments</b> folder, path to checkpoint and metrics you want to save.
To upload your checkpoint, you need to specify the config file for your experiment, which should be stored in the <b>config/experiments</b> folder. Additionally, provide the path to the checkpoint and specify the metrics you want to save.

2023-05-11 07:20 UTC, QazyBi commented on docs/Tutorials - start here/002_Uploading_data_and_checkpoints_to_s3.md
> +python innofw/data_mart/uploader.py --dataset_config_path classification/config.yaml
In shell, to achieve line continuation, you typically use a backslash() at the end of each line.

2023-05-12 19:14 UTC, sadjava commented
I guess I'm done. Check again please.

2023-05-12 19:52 UTC, merged