Dev
InnopolisUni/innofw pull request #180
Opened 2023-05-21 23:01 UTC by Dnau15

Integrated stroke segmentation model

2023-06-13 09:42 UTC, sham1lk requested changes

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +class DirSegmentationLightningDataModule(BaseLightningDataModule):
На сколько понимаю большинство года скопираванно из другого файла, предлагаю удалить код из исходного файла

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +class MyDirSegmentationLightningDataModule(
Данный класс нужно переименовать

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +            path = os.path.join(dst_path, 'img' + str(i) + '.png')
для создания дерикторий предлагаю использовать Pathlib

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +    def setup_infer(self):
думаю тест аугментации все же нужно передавать

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +            self.jpgs = self.predict_source
self.jpgs на самом деле не нужен, можно сделать что-то на подобии self.predict_source = [self.predict_source] if os.path.isfile(self.predict_source) else [self.predict_source / file for file in os.listdir(self.predict_source)]

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datasets/image_infer.py
> +class StrokeFolderInferDataset(ImageFolderInferDataset):
по сути если поправить в датамодуле этот класс будет не нужен

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datasets/semantic_segmentation/stroke_dataset.py
> +        mask = np.zeros((512, 512), dtype=bool)
часть создания маски предлагаю выделить в отдельную функцию

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/datasets/semantic_segmentation/stroke_dataset.py
> +        if str(mask_path)[-4:] != '.txt':
filename, file_extension = os.path.splitext('/path/to/somefile.ext') можно попробовать так
или mask_path.endswith('.txt')

2023-06-13 09:42 UTC, sham1lk commented on innofw/core/losses/focal_tversky_loss.py
> +ALPHA = 0.5
эти параметры предлагаю вынести в конфиг лосса

2023-06-14 12:19 UTC, Dnau15 commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +class DirSegmentationLightningDataModule(BaseLightningDataModule):
Удалил код из исходного файла

2023-06-14 12:21 UTC, Dnau15 commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +class MyDirSegmentationLightningDataModule(
Переименовал на StrokeSegmentationDatamodule

2023-06-14 12:21 UTC, Dnau15 commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +            path = os.path.join(dst_path, 'img' + str(i) + '.png')
Поменял

2023-06-14 12:22 UTC, Dnau15 commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +    def setup_infer(self):
Изменил код. Теперь в датасет передаются тест аугментации

2023-06-14 12:22 UTC, Dnau15 commented on innofw/core/datamodules/lightning_datamodules/semantic_segmentation/stroke_dm.py
> +            self.jpgs = self.predict_source
Сделал

2023-06-14 12:22 UTC, Dnau15 commented on innofw/core/datasets/image_infer.py
> +class StrokeFolderInferDataset(ImageFolderInferDataset):
Изменил ImageFolderInferDataset и удалил StrokeFolderInferDataset

2023-07-04 06:36 UTC, sham1lk approved these changes

2023-07-05 13:18 UTC, closed without merging

2023-07-05 13:20 UTC, QazyBi commented
почему-то последние изменения с ветки dev не подтягивались в pull request и билд не собирался